modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="spawnerhead"
version="${file.jarVersion}"
displayName="Spawner Head"
logoFile="examplemod.png"
credits="E"
authors="orderedchaosdev"
description='''
	Spawner Heads!
'''

[[dependencies.spawnerhead]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spawnerhead]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
